; 10進数、16進数（0x付加）のどちらでも定義可能
; *付きでポインタ参照にすることも可能
; 一部の[★文字列]はCFRUのoffset.iniを参照して書き換える必要あり
; その際、ベースアドレス08, 09を減算する必要あり
; そして対応する機能のfalseをtrueにすることで使用可能








; マップ名
MapNameTableOffset = *0xC1E78
MapNameCount = 109
MapNameFirstIndex= 0x58
; マップバンク
MapBankTableOffset = *0x54B0C
; マップ地形（ID:0001からスタート）
MapTerrainTableOffset = *0x54A54
MapTerrainCount = 383

; タイルセット
TilesetHeaderBaseOffset = 0x298B44



; トレーナー肩書き
TrainerClassNameTableOffset = *0xD90AC
TrainerClassNameCount = 107
TrainerClassNameEntryLength = 0xB
; トレーナー賞金
TrainerClassPrizeMultiTableOffset = *0x251B8
TrainerClassPrizeMultiCount = 105
; トレーナー追加データ
EnableTrainerClassEncMusic = false
TrainerClassEncMusicTableOffset = ★gClassBasedTrainerEncounterBGM
EnableTrainerClassBattleMusic = false
TrainerClassBattleMusicTableOffset = ★gClassBasedBattleBGM
EnableTrainerClassPokeBall = false
TrainerClassPokeBallTableOffset = ★gClassPokeBalls
EnableTrainerClassBaseIV = false
TrainerClassBaseIVTableOffset = ★gBaseIVsByTrainerClass

; トレーナー画像
TrainerSpriteImageTableOffset = *0x33EB0
TrainerSpritePaletteTableOffset = *0x33EC0
TrainerSpriteYPosTableOffset = *0x375E8
TrainerSpriteAnimPointerTableOffset = *0x3F060
TrainerSpriteCount = 148
