; 10進数、16進数（0x付加）のどちらでも定義可能
; *付きでポインタ参照にすることも可能
; 一部の[★文字列]はCFRUのoffset.iniを参照して書き換える必要あり
; そしてその上のfalseをtrueにすることで使用可能












; トレーナー肩書き
TrainerClassNameTableOffset = *0xD90AC
TrainerClassNameCount = 107
TrainerClassNameEntryLength = 0xB
; トレーナー賞金
TrainerClassPrizeMultiTableOffset = *0x251B8
TrainerClassPrizeMultiCount = 105
; トレーナー追加データ
EnableTrainerClassEncMusic = true
TrainerClassEncMusicTableOffset = 0x110D8FC
EnableTrainerClassBattleMusic = true
TrainerClassBattleMusicTableOffset = 0x110D824
EnableTrainerClassPokeBall = true
TrainerClassPokeBallTableOffset = 0x11005A4
EnableTrainerClassBaseIV = true
TrainerClassBaseIVTableOffset = 0x10F2E00

; トレーナー画像
TrainerSpriteImageTableOffset = *0x33EB0
TrainerSpritePaletteTableOffset = *0x33EC0
TrainerSpriteYPositionTableOffset = *0x375E8
TrainerSpriteAnimPointerTableOffset = *0x3F060
TrainerSpriteCount = 148
